---
title: "Instructions for the admin use of the SNB package"
author: "Lotte Schlicht & Mihai Valcu"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{SNBadmin}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This file comprises overall instructions for the use of the SNB package as a tool for database management and data processing.
If you are interested to handle the data itself, call `vignette('SNBuser')` instead or, if you read this in the web interface,
choose the proper entry using the pull-down menu on the right.

This introduction gives you an overview over what to do when and which functions may be of importance.

### Instructions for data collection

#### General notes
  - When plugging in an SD or CF card, never "check the file system" or "format card" if Windows asks you to, or manually format cards containing data.
  - As with all raw data, never cut-and-paste and files, rather use copy-paste-delete.

#### Field information: SD cards changes and more
  - Note: The function `plot_from_raw` can be used to plot raw BOX001.TXT files in the field.
  - Plug your personal transponder into the nest opening before pulling the SD card.
  - Note the time when you pull the transponder out of the nest opening.
  - Avoid pulling the SD card while data is being written (for example, wait for a few seconds after removing your personal transponder from the nest opening)
  - If your transponder is not available, try to avoid using someone else's transponder. Use one of the spare non-assigned transponders instead.
  - SD cards that do not contain data should have the colored dot on the labels facing upwards and the contacts downwards. After replacing the SD card, please make sure to turn the SD card that contains data around so that the contacts are facing upwards and the colored dot is no longer visible. This will make copying the SD cards much easier.
  Note: If the green dot is not facing you, the SD card may contain data. In this case, verify that you have not been at the box before (do you actually have to change the SD card?), and use one of the spare SD cards instead, making a comment onto the data sheet.

#### Full upload instructions for SD cards

##### Overview:
  - Use the User Interface `butler()` to do one of the following tasks:
  - Copy .txt files from the SD cards to the server,
  - prepare new SD cards, upload the data from the server to the database.
  - Enter the times when the SD cards were pulled.
  - Upload the data from the server to the database.
  - Enter the times when the SD cards were pulled.
  - Process data from the raw format (tables b001 - b277) into the EVENTS table and run some quality checks.

  - The the  `butler()` can be also accessed as an RStudio (v0.99.878 or later) add-in.

##### Notes:
  - If you copy and upload the data of each field team member one after the other, the later data entry will be much easier for the field team.
  - Make sure to replace broken cards (physically or electronically broken) by new cards using the function `prepare_SD()`.
  - The field team can only enter the data (author, date, time, box, ...) __after__ the SD cards got copied __and__ the data uploaded to the database.
  - Ask the field team to enter the times when the individual cards were pulled at the internal website.


##### Copying instructions for CF cards
  - Open the CF card.
  - Open the path to the raw data (type `getOption("path.to.raw")` into R to fetch path information).
  - Rename any folders on the CF card that are named by a date by pasting "CF" behind the date.
  - Copy the entire folder to the server and verify that the number of boxes that were copied is correct.
  - Check if a box has multiple files (for example a folder '165' and in addition a folder '165old'). If so, create a new date folder (YYYY.MM.DD_2CF), and copy the more recent file into the new folder.
  - Move the copied folders on the CF card to the folder "uploaded".
  - Safely remove CF card.
  - Run the functions `scidb_snbUpdater`, `update_DATA_QUALITY`, and `upload_events` to upload the data.

##### Troubleshooting
  - All data can be copied manually to the server (both SD- and CF-card data; type `getOption("path.to.raw")` into R to fetch path information). Consult previous data to know what to copy. If data is copied manually, please make sure that the data arrived before deleting the original files.
  - The user "bt" with password "bt" (default user for the field team) has access to the file_status table in the SNBatWESTERHOLZ database, where the time at which an SD card was pulled is saved. If you already submitted your data, and then discover a potential error, you can manually correct this error. Note that you will onnly have writing access to the columns "datetime_" and "author".

  - If in doubt about anything during the copying process, check whether the data arrived on the server. If not, try again, or copy-paste-delete manually.

  - Sometimes cards break on an electronic level. If you have problems with a specific card, first try a different reader slot (slots get worse with wear and tear and need to be exchanged every once in a while). If you again encounter problems, try a different reader or try multiple times and do not use the card again in the field. If you can't get the card working at all, mark it accordingly, and store the card somewhere safe (in case we ever find a way to solve that problem).

  - Handle the reader with care. There should not be any harsh sounds when entering an SD card into a reader, they should slide in and out easily, and do not need to be pushed in with force - a bit of gentle pressure is sufficient. Even so, reader slots will break down after some time with wear and tear. If you have trouble with a specific slot with multiple cards that work without problems in a different slot, replace the slot.

##### Miscellanea
  - Settings for the LabPal:
       - Old LabPals: Horizontal Banner, Point Size 14;
       - New LabPals: PathPanel, 20pt bold