---
title: "Instructions for the end user of the SNB package"
author: "Lotte Schlicht & Mihai Valcu"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{SNBuser}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Install SNB package using instructions on http://scidb.mpio.orn.mpg.de.

The most relevant functions of the SNB package are summarized below.
Please use `?function_name()` in order to access the respective help files. All
help files contain working examples, which can be used to assess the application
of the individual functions.

If you need to upload data or perform database management, call `vignette('SNBadmin')` instead or, if you read this in the web interface,
choose the proper entry using the pull-down menu on the right.


### Database overview: SNBatWESTERHOLZ
| Table name   | Depending on                               | Is used for          |
|:-----------  |:------------------                         |:-----------          |
| b001-b277    | //ds/.../BOX001.txt                        | DATA_QUALITY, EVENTS |
| file_status  | //ds/.../BOX001.txt, data entry interface* | DATA_QUALITY         |
| DATA_QUALITY |b001-b277, file_status                      | EVENTS               |
| EVENTS       | b001-b277, DATA_QUALITY                    | --                   |

*http://scicomp.orn.mpg.de:3838/SNBatWESTERHOLZ/

### Notes

- The code of any function can be assessed by typing the function name only
    (i.e. without parantheses).

- For a full list of the package functions, click on the "Index" link on the
    bottom right of any help page of the package.

- To get information about the location of the raw data .txt files, type
    `getOption('path.to.raw')` (Note that copy-pasting the path will only work on Linux.)

- If you find bugs, please let the package authors know.

- If you come across functions that would be handy for all SNB users, please point this out
    to the package authors.

- Path to the wiki page: (http://scidb.orn.mpg.de/scidb/doku.php)



### Functions
1.  Data handling

    - feeding
    - ivi
    - queryEvents
    - queryResidents
    - sleep


1.  Plotting functions

    - actogramPlot
    - feedingPlot


1.  Auxiliary functions (a few example)

    - boxes
    - breedingStage
    - char2date
    - fast_POSIXct
    - int2b

    For a complete list of functions check ?SNB and browse the help files.


1.  In-depth data handling (for experienced users or specific needs)

    - posthoc_combineEvents
    - events

